### ISSUE TITLE
Generate a specific template/asset

### ISSUE THREAD

**Issue by playground** [connected-web/node-hag#3]
Is it possible to only generate asset for a specific template?

**Comment by johnbeech** [comment]
You can pass in a glob string, or a specific file name, for example: `hag generate specific-instruction.json` - does that do what you need?

**Comment by playground** [comment]
yes, thanks.  Will let you know how it goes once I start playing with it.

**Comment by playground** [comment]
One more question, what about referencing external image file from the template?

**Comment by Markavian** [comment]
To bring images into your HTML templates you can either put them in `data` or `templates` and refer to them using an absolute relative path, e.g.`/data/images/myimage.png` or `/templates/images/myimage.png`.

Here's a worked example:
- https://github.com/mkv25-games/salvage-crew/blob/master/generator/data/contacts/false-contact.json
- https://github.com/mkv25-games/salvage-crew/blob/master/generator/instructions/card-contacts.json
- https://github.com/mkv25-games/salvage-crew/blob/master/generator/templates/cards/event-contact.html

The `false-contact.json` data:
```
{
  "title": "False Contact",
  "instructions": ["As you approach the location of the blip, your scanner stops making noise. Must have been a false positive."],
  "background": "/data/images/false-contact.png",
  "theme": {
      "primaryCardColour": "#002C67",
      "secondaryCardColour": "#333333"
  },
  "asset-type": "contact",
  "asset-id": "false-contact"
}
```
Is fed to `event-contact.html` template by the instruction in `card-contacts.json`:
```
{
    "asset": "images/cards/contact/false-contact.png",
    "template": "/cards/event-contact.html",
    "renderer": {
        "$ref": "data/renderer/standard-card.json"
    },
    "data": {
        "$ref": "data/contacts/false-contact.json"
    }
}
```

When rendering, `background-image: url('{{background}}');` in `event-contact.html` is replaced with `/data/images/false-contact.png`, which is served up from the local file system via `hag generate`.

**Comment by playground** [comment]
Thanks, this is very helpful.  Can you point me to the documentation?

**Comment by johnbeech** [comment]
Will have to write some documentation first; have raised #4 - watch that space.

**Comment by playground** [comment]
@johnbeech how do you pass in glob string in the command?
I tried this but it's coming back with no matches found: [asset:test.png]
What am I doing wrong?

hag generate [{"asset":"test.png","template":"/test.hbs","renderer":{"type":"webshot","size":{"width":400,"height":500}},"data":{"$ref":{"title":"Current 天氣 你好","backgound":"/templates/images/test.jpg","data":{"location":"亚特兰大, GA","icon":"/templates/images/wxicons/test.png","current":"82°F","phrase":"CLEAR","hi":"98","lo":"69"},"theme":{"primaryCardColour":"#002C67","secondaryCardColour":"#333333","fontColor":"#999"},"author":"someone"}}}]
